public class Bankdetails {
    //variable
   // Long Accnumber=232323;
    
    
    
    
    //methods
    //non parameterized method
  /*  public void displayBlance(){
        
        //opertions
        long balance=Accnumber+1;
        system.debug('the balacne '+balance);
        
    }*/
    //parameterzied method
    public void displayBalance(Long Accnumber){
        long balance=Accnumber+1;
        system.debug('the balacne '+balance);
        
        
    }

}