public class Demo2 {
    //Variables
    integer a= 50;
    string s='demo2 class';
    date dat=system.today();
   	integer b= 35;
    
    Public void displaymethod (){
        system.debug('a value is '+a);
        system.debug('String Vaule is'+S);
        system.debug('date of the system '+dat);
    }
    public void display2method(){
        integer c=a+b;
                system.debug('c valuse '+c);
      
    }

}