public class interestcalculation {
    //varibale
    
   // Void method 
   /* public void cal(integer amount, integer intrate){
        integer sum=amount/intrate;
        system.debug('the sum value ' +sum);
        
    } */
    //non void method 
     public Integer cal(integer amount, integer intrate){
        integer sum=amount/intrate;
		Return sum;        
    }
    public string cal1(string name){
        string myname='sudhakar';
        return myname;
    }
    public boolean cal3(boolean b){
        boolean status=b;
        return status;
    }
}