public class poly_Demo {
    
    //Vairable
    
    //Methods (miltiple methods with the same name and same patmertes )
    public void add(integer a, integer b){
        integer sum=a+b;
        system.debug('the sume of firest method ' +Sum);
        
    }
    public void add(integer a, integer b, integer c){
        integer sum =a+b+c;
        system.debug('the sume of second method '+sum);
            }
    public void add(integer a, integer b, integer c, integer d){
        integer sum =a+b+c+d;
        system.debug('the third method '+sum);
    }
}