public class setclass {
    
    public void setmethod(){
        Set<string> mySet=new set<string>();
        mySet.add('shan');

        myset.add('prasanth');
        myset.add('sudhak');
        system.debug('the set methode values ' +mySet);
              system.debug(mySet.contains('shan'));

        mySet.add('sudhak');
        mySet.remove('sudhak');
        system.debug(' after removing'+myset);
        system.debug(myset.size());
        mySet.clear();
        system.debug('clear to set' +mySet);
        
    }

}